hw done, please check
yanikr/nodejs-homework-rest-api pull request #3
Opened 2023-01-21 18:57 UTC by yanikr

2023-01-22 16:21 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-22 16:21 UTC, KhYulian commented on controllers/authController.js
> +  const isPasswordValid = await bcrypt.compare(password, user.password);
Якщл юзера не знайдено ви отримаєте помилку через user.password. Можете використати optional chaining user?.password

2023-01-22 16:21 UTC, KhYulian commented on controllers/authController.js
> +  return res.status(204).json();
Краще використати метод .end() замість json()/ якщо нічого не повертаєте у відповіді

2023-01-22 16:21 UTC, KhYulian commented on middlewares/index.js
> +    next(res.status(401).json(Unauthorized("Not authorized")));
return next...

2023-01-22 16:21 UTC, KhYulian commented on middlewares/index.js
> +    next(res.status(401).json(Unauthorized("Not authorized")));
в catch передавайте в next помилку - next(error)

2023-01-23 07:30 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-23 07:30 UTC, KhYulian commented on middlewares/index.js
> +      return next(res.status(400).json(BadRequest("missing fields")));
в catch передавайте в next помилку - next(error) - це стосується усього коду

2023-01-23 08:12 UTC, yanikr commented on middlewares/index.js
> +      return next(res.status(400).json(BadRequest("missing fields")));
це ж не try-catch конструкція. Тут звичайний іф

2023-01-23 10:41 UTC, KhYulian commented on middlewares/index.js
> +      return next(res.status(400).json(BadRequest("missing fields")));
В next передавайте виключно об'єкт помилки (або викликайте без аргументів, якщо просто хочете предати виконання в наступну middleware) 
передавати в next res.status(400).json(BadRequest("missing fields") - це дуже груба помилка. 
if це чи не if значення немає

2023-01-23 10:42 UTC, KhYulian commented on middlewares/index.js
> +      return next(res.status(400).json(BadRequest("missing fields")));
перегляньте увесь код і всюди поправте, де є схожа помилка

2023-01-23 17:56 UTC, KhYulian approved these changes
Чудова робота!

2023-01-23 17:56 UTC, merged